SELECT
  TRY_TO_DATE(o2d.onboarded_date, "dd/MM/yyyy") AS onboarded,
  o2d.id AS project_id,
  o2d.client AS client_name,
  o2d.project AS project_name,
  o2d.category,
  o2d.spoc AS spoc_doer,
  o2d.project_lead AS project_managers,
  o2d.project_type,
  o2d.vendor,
  o2d.total_revenue,
  COALESCE(o2d.vendor_cost, 0) AS vendor_cost,
  o2d.first_tranch,
  TRY_TO_DATE(o2d.planned, "dd/MM/yyyy") AS planned_completion,
  TRY_TO_DATE(LEFT(o2d.actual, 10), "dd/MM/yyyy") AS actual_completion,
  o2d.status,
  o2d.mdo,
  o2d.unit,
  TRY_TO_DATE(LEFT(o2d.first_tranch_date, 10), "dd/MM/yyyy") AS first_tranch_date,
  o2d.pc_update,
  o2d.`source`,
  o2d.practice,
  o2d.crm_update,
  o2d.lead_name,
  o2d.client_email,
  o2d.client_phone,
  o2d.group,
  o2d.city,
  o2d.sow,
  o2d.attached_proposal
FROM
  {{ source( 'o2d_source','dim_o_2_d' )}} AS o2d